name: Setup Bun environment
description: Set up JS runtimes, cache and install dependencies with Bun.

runs:
  using: composite
  steps:
    - name: Setup JS runtimes
      uses: jdx/mise-action@94c60b39bc2d90ab2f9bab27f38d3cc4812c1834 # v5.1.0
    - name: Cache dependencies
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock', '**/mise.toml') }}
    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
