name: Setup Bun environment
description: Set up JS runtimes, cache and install dependencies with Bun.

runs:
  using: composite
  steps:
    - name: Setup JS runtimes
      uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
    - name: Cache dependencies
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock', '**/mise.toml') }}
    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
